@host = https://localhost
@port = 7000
@RehApp.API_HostAddress = {{host}}:{{port}}
@organizationId = 0aa42b09-f2b2-47b5-b520-64ccee98ec66
@patientId = 9c9b8671-82a1-4bb4-5fce-08dcacd51e63
@doctorId = 03407503-ea31-4d18-9aff-1bc95ff173e6
@token = CfDJ8KppXvv35Z1MvC9Y7rPN44Y7LtId42KEXH7NyMilXwmJ4FQwmC7Gaak8EKXpkqtMNtJ6Y7fplpLl1MApV0dyDSGy2uVa1-pxRSXF_zB6kpcQXL0i0sZxSXZc1apIFenis18buA80fFsJdDjVG_GYQabXaqLPthRpKU3x-KkbqhXr0QGrnvmZkifY5clRrqQrsHX5QpCMO895ZQIbF0DApYRn2kK81GKNjqA_BwUyK1GxtvROjRoYSqaBb9BTAcagbj1Dco3p3PY-iM_3E1IIilLKZpVvptiuw0nyChOaUE9klC8s-Nf-ScGEY2xlqhrXRBHaofRjIOFL3fW_BiMBv6iIuhIJPtxML2lbT-DHnrlQF0_BX2U0p0QlEWalGoopzlOjppEKlHsl7ZE2juk_FMCZhd3YmOjs5Xpil2gxdxP11A3LyD1ewAzd7yj0K5rlJPLjtaHdsJ53Jmb_Hn0nvLfM2bBs1FUkJsTRHQx0qJZkmSZL_yCJqyjG6YbrcygbB98HMpKfO8qL0sAm_gD5jw-XappSdKI4Ia3RafrtVawapld1dyoqUGaSV2mkeWBXEEG20j-tqTLpRrmv4PtjsPwuCHdbU2ZA1hpATXhVNEiZXfQML0gWnBpfP7ZFjo6JRfU4iF6hFvXZHXwiVe0jEMZXq3q2aCj9ReEZ3mtPX1P7ERAykEB-fXU_B2cznvPXAvuu6-BJFnaNfhYN1zHE5euH0-bwibJigd4Tmbci2umXZTorBq4eWiSVt_U_mL38HFx16CYgVRndnB6FxDTUaQesOqegfjeq9-QbNfD2ecgVL67YD-9T0_wmjQEI3XSuSg

### Create a new user
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "StrongPassword123!",
  "firstName": "Jane",
  "lastName": "Doe",
  "userRole": "Doctor",
  "specialization": "Cardiology",
  "licenseNumber": "JD12345",
  "street": "123 Main St",
  "city": "New York",
  "zipCode": "12345",
  "country": "USA"
}

### Create a admin user
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "StrongPassword123!",
  "firstName": "Bruce",
  "lastName": "Wayne",
  "userRole": "Admin", 
  "street": "Wayne Manor",
  "city": "Gotham",
  "zipCode": "88-888",
  "country": "USA",
  "adminLevel": "System"
}

### Login user
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "StrongPassword123!"
}

### Get Current User
GET {{RehApp.API_HostAddress}}/api/identity/current
Authorization: Bearer {{token}}


### Create a new organization
POST {{RehApp.API_HostAddress}}/api/organizations
Content-Type: application/json

{
  "name": "Centrum Fizjoterapii Zdrowie",
  "description": "Nowoczesne centrum fizjoterapii oferujące szeroki zakres usług rehabilitacyjnych dla pacjentów w każdym wieku.",
  "street": "ul. Kwiatowa 15",
  "city": "Warszawa",
  "zipCode": "00-001",
  "country": "Polska"
}

### Get Organization by ID
GET {{RehApp.API_HostAddress}}/api/organizations/{{organizationId}}
Accept: application/json

### Create a new patient
POST {{RehApp.API_HostAddress}}/api/patients
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "dateOfBirth": "1990-01-01",
  "conditionDescription": "Ból pleców",
  "street": "ul. Główna 1",
  "city": "Warszawa",
  "zipCode": "00-001",
  "country": "Polska",
  "organizationId": "{{organizationId}}"
}

### Get Patient by ID
GET {{RehApp.API_HostAddress}}/api/patients/{{patientId}}

### Create a new visit
POST {{RehApp.API_HostAddress}}/api/visits
Content-Type: application/json

{
  "date": "2024-07-30T10:00:00Z",
  "description": "Konsultacja",
  "createdByUserId": "{{doctorId}}",
  "patientId": "{{patientId}}",
  "organizationId": "{{organizationId}}"
}