@host = https://localhost
@port = 7000
@RehApp.API_HostAddress = {{host}}:{{port}}
@adminToken = CfDJ8KppXvv35Z1MvC9Y7rPN44bJgXJHD17Wg84bYkKPmSxGuaTGTm5TaX9ABj8UBwuq9-jm6mHYiE9DyRS8xNcwf_7xwGziRB-cTsKfkvcaVZtb5PbiLcb46Z37etYQc7lruOsnKC1vCRRZAyxqHOo4rDBic5Kyh82UlTOeFjO07NoLNyxp0bRzxR9N4u3pItZKB_hzx-HEjtNjaTV_u0_IIp8nA4NAE0rEXwdKdbfZrXs9ARvZHXFXPHqwTzoL7JAS_dwbaS7vAyvx71W6Lwi_einoTg1HQBF2sMElPi3rtOX5KI-_hTIZLbasEXlwNFIW8ymil8TyFeQVN8Rx2MH5DewEcCatqQs_GJ28hBhJ6EqXEi8BD-FC4d5ZxSkKVqVJQoNwTU8BkqcNkZkYNBboMdEoBtCLuYRCUzkczZALmsgXcqQLSCXt-NFuJ27rVnM4yTbXiIThRdxRi6zbngRR-zsrR0gZUzsuoMsmmdcsWJcfybw-gwk3-h5m9MSHD1vBb9Xlspl7bGDdwiOGkPlHsir0znNA-rGlxD7uG0dJuUt5Q4AlSsMv7EPIqpC2LnNuSVhiz7RbF2DzQb6b3b3h83P5ZPXAGguJiHr1RPbFwq7QccWDSSkJgWTr2bPUj74MZbSoT4d2KEXvYn2vCDN-cVOH7JwbC0000zQry7XmOYUQKHaA8tDFb7RjjaH4zQyBYbp9ypnPhAozzHllI_FO9GQt7TEbIbQcViQMD9-qEnQUdM-XUEU1NZaNE9b9_p_J2B5Rm1vpX5iTx4OBbyb_Wdmj5IbmTmBMOLrGkHTwsXaG
@otherToken = CfDJ8KppXvv35Z1MvC9Y7rPN44aDbMXAlCqedNxNwr9gP7DhViqpUtdpgvzG1n09M9Ow4anApbfuIA30-wYbhR7k0A22jmOxmiyfFIErG62fIVR_PwcJH8rMujvcMwp78xgCVXv_U4V2cZjXIfwmeX1xOzTPOShcx2DZiUnvxufe6_dwNGk4TiZj9swrEf4TeVc4RokWmWmKDT7mu3zsoYdwUqvUMrji7Bmjtvex_nVQ-ROrdh_9XeHzUT3LU92IZV4Fpn_WaXjVQAy-zS6VlW2RUUhqC2GV2GntdSRmb9gFB0YLAIw1zn8MAl7dBPVwK0biaSJsZiWBwh6GyKPne5CcLzuPaAfOd_rZuBFvgZT_EMXkzT-T55yTpriWyBzVdmgIpAJ0L8PnWL_dkpDClAVjFo9FE2FbFZhSl9mBwFqSWdendb_1KLgFDLhRZhCyI1YvTFUKptDJQDAZCDPmiWpHCgdw8emws2GF9-QVNK8-4KExsht04OoENxxBZ_psgkWNzRr_MNc16xsoERQLwJsMXR4kjkHLgB9UfB8NMdD1Q62tqFe4q1K6XpJjEU93OvIje7lNwJ6OJ_sgVqGNixWG6rmFL3Pvgf3RYoTiDScrxBXyF6bc1Ros9t8bIfb9JSDo_rJkHnUhrdHUibrkR30vXV-Mudx65RxXy0m_JgJS9quW0QibBqOTHgWDJ9gGADE0F0wXHrYEi7WcnRbg0hPzTZzdhEeHncTzW7tq9vTTi7Dx7r9L_DsPyF8Zdv1sOzUl8n-sKuHGDoZl9COuzA8eMHLVx-U2jPyilAo7pm-ADE4yxjhUhI900xVyqZwVsxz2Vo251qsq6JhnaCmEwTFX8X0
@adminGuid = e9f9a7c8-31bd-4103-80ca-2420f31c61a3
@userId = 797ee785-f57d-4a56-973e-948890b1e6f3
@organizationId = 7e23355c-4b98-4578-2d6c-08dcb1b4a917
@johnDoeDoctorGuid = 36bc25ec-7106-45d4-936a-9e2878af6144
@johnDoeDoctorToken = CfDJ8KppXvv35Z1MvC9Y7rPN44Z1aidaxyar3UiCdeqUHzpT6Qm3graUzDPMJU82yHG7CwsO0kBMR8yEbv0RWtUkEYkI1IL4KlXlelEnnkYvvgRXXa3W_4aG8saf0qT6BO0xcZSg0HP_V89ISMh8lG8JEvsn6ceD3e4nUEAWoQvxzStN3W0YvbqzLtodsR2uec3xtZJRVwDPHU2wzsz_GIwy5FJ-E4GuWnnGx5SRvg7dWw6B5sKocKyIAUrEtRxXJRsktVSYSuLGN6uvX6Mn0efGh487eANiWn8tWUZ__1xEvwrKy6Zy_F_eB-h52wbVKCzQJe0O3Ia3n2CLuTHh9E65CkF7JN_kqrkRoi5bvjyBkbnTaI5qznmBX9HGyAdSR1-aLaIZnhNh7pL3nxHfejMJc_RkKIgXRAEQMoxojSgNIi_s2r1SzHTL36QJClqqTTgngPpewsQ5jRLL_70Vmu7FDHHufwDVahaR9zM4lBoTxf2WZcd4a5UBAycPDPpDQ0ooaZNjra3p-Rcuhhi3n-mCf-4BVlKh6ezhqwniJjPZYPWMNo-G8yhVOkhfBqwfkZHDp5RYZ9WRIfqh0mhTxPXSc-iWkh3rvVlyUU-_VRPK0IdzD81wxIGjuImOC1jARAPqSqgkMK0Jh9ISIHtEj2-Epu-CYcBzBI0_sQSTzk6vpkFgum1rQ3gYSQn-UaIG8d2e7VZmpUnH9JJgdWlDF7BqsLp5dYXtgrVI5auJ3Aqyy7ZkENzTlvG1pWgtlkUv4JvpuuUfRHl87pF0h4RH834LP3j-cnYIst5WD4Ghu-NnXTbrdCgzCL9KQK1J0_KdbB8Jfg


### Login as 'Admin'
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "SecurePassword123!"
}

### Create a new user with 'Admin' role
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "SecurePassword123!",  
  "firstName": "Bruce",
  "lastName": "Wayne",
  "userRole": "Admin",
  "adminLevel": "SystemAdmin",
  "street": "Main Street",
  "city": "Gotham",  
  "zipCode": "12-345",
  "country": "USA",  
  "phoneNumber": "123456789", 
  "pesel": "12345678901"    
}

### Create a new user 
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "emma.watson@example.com",
  "password": "ExamplePass!456",
  "firstName": "Emma",
  "lastName": "Watson",
  "street": "789 Oak Avenue",
  "city": "Metropolis",
  "zipCode": "87-123",
  "country": "USA",
  "phoneNumber": "123123123",
  "pesel": "12312312345",
  "userRole": "OrganizationAdmin"
}

### Update user information
PATCH {{RehApp.API_HostAddress}}/api/identity/update
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "id": "{{adminGuid}}",
  "email": "admin@example.com",
  "firstName": "Bruce",
  "lastName": "Wayne",
  "role": "Admin",
  "phoneNumber": "123456789",
  "pesel": "12345678901",
  "address": {
    "street": "Main Street 2",
    "city": "Gotham",
    "zipCode": "12-345",
    "country": "USA"
  },
  "adminLevel": "System Administrator"
}

### Update user information
PATCH {{RehApp.API_HostAddress}}/api/identity/update
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "id": "e9f9a7c8-31bd-4103-80ca-2420f31c61a3",
  "firstName": "Bruce",
  "lastName": "Wayne",
  "phoneNumber": "123456789",
  "pesel": "12345678901",
  "address": {
    "street": "Main Street 2",
    "city": "Gotham",
    "zipCode": "12-345",
    "country": "USA"
  },
  "adminLevel": "System Administrator"
}

### Create a new user with 'Doctor' role
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePassword123!",
  "username": "john.doe",
  "firstName": "John",
  "lastName": "Doe",
  "userRole": "Doctor",
  "specialization": "Cardiology",
  "licenseNumber": "987654321",
  "street": "Elm Street",
  "city": "Springfield",
  "zipCode": "54321",
  "country": "USA",
  "phoneNumber": "987654321",
  "pesel": "10987654321"
}

### Login as 'Doctor'
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePassword123!"
}

### Create a new user with 'Physiotherapist' role
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "jane.smith@example.com",
  "password": "SecurePassword123!",
  "username": "jane.smith",
  "firstName": "Jane",
  "lastName": "Smith",
  "userRole": "Physiotherapist",
  "specialization": "Orthopedics",
  "licenseNumber": "654321987",
  "street": "Oak Street",
  "city": "Metropolis",
  "zipCode": "67890",
  "country": "USA",
  "phoneNumber": "654321987",
  "pesel": "21098765432"
}

### Login as 'Physiotherapist'
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "jane.smith@example.com",
  "password": "SecurePassword123!"
}

### Create a new user with 'Nurse' role
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "alice.jones@example.com",
  "password": "SecurePassword123!",
  "username": "alice.jones",
  "firstName": "Alice",
  "lastName": "Jones",
  "userRole": "Nurse",
  "department": "Pediatrics",
  "licenseNumber": "321654987",
  "street": "Pine Street",
  "city": "Smallville",
  "zipCode": "98765",
  "country": "USA",
  "phoneNumber": "321654987",
  "pesel": "32109876543"
}

### Login as 'Nurse'
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "alice.jones@example.com",
  "password": "SecurePassword123!"
}

### Create a new user with 'OrganizationAdmin' role
POST {{RehApp.API_HostAddress}}/api/identity/create
Content-Type: application/json

{
  "email": "clark.kent@example.com",
  "password": "SecurePassword123!",
  "username": "clark.kent",
  "firstName": "Clark",
  "lastName": "Kent",
  "userRole": "OrganizationAdmin",
  "adminLevel": "Organization",
  "street": "Maple Street",
  "city": "Metropolis",
  "zipCode": "54321",
  "country": "USA",
  "phoneNumber": "987654321",
  "pesel": "10987654321"
}

### Login as 'OrganizationAdmin'
POST {{RehApp.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "clark.kent@example.com",
  "password": "SecurePassword123!"
}

### Get current user information
GET {{RehApp.API_HostAddress}}/api/identity/current
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### Get all users
GET {{RehApp.API_HostAddress}}/api/identity/all-users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### Create a new organization
POST {{RehApp.API_HostAddress}}/api/organizations/create
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "Rehab Center",
  "description": "Providing top-notch rehabilitation services.",
  "street": "789 Health Ave",
  "city": "Wellness City",
  "zipCode": "34-567",
  "country": "Healthland",
  "phone": "555-987-6543",
  "email": "contact@rehabcenter.com",
  "additionalInfo": "Specializing in physical therapy and rehabilitation.",
  "taxNumber": "1234567890"
}

### Get all organizations
GET {{RehApp.API_HostAddress}}/api/organizations
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### Get organization by ID
GET {{RehApp.API_HostAddress}}/api/organizations/7e23355c-4b98-4578-2d6c-08dcb1b4a917
Authorization: Bearer {{adminToken}}
Content-Type: application/json


### Add user to organization
POST {{RehApp.API_HostAddress}}/api/organizations/add-user
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "userId": "{{userId}}",
  "organizationId": "{{organizationId}}"
}

### Get all users not in organization by id
GET {{RehApp.API_HostAddress}}/api/organizations/users-not-in-organization/7e23355c-4b98-4578-2d6c-08dcb1b4a917
Content-Type: application/json

### Get user by id
GET {{RehApp.API_HostAddress}}/api/identity/{{userId}}
Content-Type: application/json

### Get all users in organization by id
GET {{RehApp.API_HostAddress}}/api/identity/users-in-organization/2665e4f1-0d99-4fc2-2d6b-08dcb1b4a917


### Create a new patient
POST {{RehApp.API_HostAddress}}/api/patients/create
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "firstName": "asdas",
    "lastName": "dsadas",
    "dateOfBirth": "2024-07-20T22:00:00.000Z",
    "conditionDescription": "qwsdas",
    "street": "qweda",
    "city": "dasdas",
    "zipCode": "76-767",
    "country": "Poland",
    "pesel": "12345678909",
    "phoneNumber": "123321123",
    "organizationId": "7e23355c-4b98-4578-2d6c-08dcb1b4a917"    
}

### Get patients for organization by id
GET {{RehApp.API_HostAddress}}/api/patients/organization/{{organizationId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### Get all visits for user by id for organization by id
GET {{RehApp.API_HostAddress}}/api/visits/user/{{johnDoeDoctorGuid}}/organization/{{organizationId}}
Authorization: Bearer {{johnDoeDoctorToken}}

### Get visit by id
GET {{RehApp.API_HostAddress}}/api/visits/a79f4f60-6b9b-4945-0bec-08dcb3cd599b
Authorization: Bearer {{johnDoeDoctorToken}}

### Update Visit
PUT {{RehApp.API_HostAddress}}/api/visits/a79f4f60-6b9b-4945-0bec-08dcb3cd599b
Authorization: Bearer {{johnDoeDoctorToken}}
Content-Type: application/json

{
    "id": "a79f4f60-6b9b-4945-0bec-08dcb3cd599b",
    "date": "2024-01-16T23:00:00.000Z",
    "description": "asdsada"
}

### Change password
POST {{RehApp.API_HostAddress}}/api/account/change-password
Authorization: Bearer {{johnDoeDoctorToken}}
Content-Type: application/json

{
    "id": "36bc25ec-7106-45d4-936a-9e2878af6144",
    "currentPassword": "SecurePassword123!",
    "newPassword": "Secure!Password1"
}